server:
    port: 7001

spring:
    #本地配置
    #profile:
        #active: native
    application:
        name: @project.artifactId@
    # git管理配置
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/ceylog/springcloud.git
                    searchPaths: config-repo
                    #username: username
                    #password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:1111/eureka/



    